version: 2
dependencies:
  pre:
    - sudo add-apt-repository ppa:koffeinflummi/armake; sudo apt-get update; sudo apt-get install armake
jobs:
  build:
    docker:
      - image: python:3-alpine
    steps:
      - checkout
      - run:
          name: Build with armake
          command: |
            sudo add-apt-repository ppa:koffeinflummi/armake -y
            sudo apt-get update -qq
            sudo apt-get install armake -y
            make --version
            armake --version
            make -j 3
      - run:
          name: Validate SQF and Config style
          command: python tools/sqf_validator.py && python tools/config_style_checker.py
  deployment:
    docker:
      - image: python:3-alpine
    branch: master
    requires:
      - build
    steps:
      - checkout
      - deploy:
          name: Deploy
          command: |
            pip install pygithub pygithub3
            python3 tools/deploy.py
